const recentImages = [
    "arches.jpg",
    "at_the_waters_edge.jpg",
    "dust_and_tallgrass.jpg",
    "effie_yeaw_nocturne.jpg",
    "great_blue_heron.jpg",
    "la_cygne_sunrise.jpg",
    "leland.jpg",
    "morning_mist_at_stoll_memorial_park.jpg",
    "mothers_embrace.jpg",
    "oceanic_reverie.jpg",
    "procida_walkway.jpg",
    "the_banjo_player.jpg",
    "the_clouds_over_canmore.jpg",
    "winters_journey.jpg",
];
