const portraitImages = [
 {"thumb_image": "images/Portraits/leland.jpg", "full_image": "images/Full-Gallery/leland.jpg", "alt_text": "leland", "title": "Leland", "artist": "J. Grant Merrill", "medium": "Pastel", "type": "Painting", "width": "12.0", "height": "16.0", "date_created": "2024-12-01", "collections": "", "status": "not_for_sale", "price": ""},
 {"thumb_image": "images/Portraits/mothers_embrace.jpg", "full_image": "images/Full-Gallery/mothers_embrace.jpg", "alt_text": "mothers_embrace", "title": "Mother's Embrace", "artist": "J. Grant Merrill", "medium": "Oil", "type": "Painting", "width": "16.0", "height": "12.0", "date_created": "2025-05-01", "collections": "Portraits", "status": "not_for_sale", "price": ""},
 {"thumb_image": "images/Portraits/portrait_of_claire.jpg", "full_image": "images/Full-Gallery/portrait_of_claire.jpg", "alt_text": "portrait_of_claire", "title": "Portrait of Claire", "artist": "J. Grant Merrill", "medium": "Pastel", "type": "Painting", "width": "11.0", "height": "14.0", "date_created": "2023-04-01", "collections": "", "status": "gifted", "price": ""},
 {"thumb_image": "images/Portraits/portrait_of_kelly.jpg", "full_image": "images/Full-Gallery/portrait_of_kelly.jpg", "alt_text": "portrait_of_kelly", "title": "Portrait of Kelly", "artist": "J. Grant Merrill", "medium": "Oil", "type": "Painting", "width": "16.0", "height": "20.0", "date_created": "2024-03-01", "collections": "", "status": "not_for_sale", "price": ""},
 {"thumb_image": "images/Portraits/sarah.jpg", "full_image": "images/Full-Gallery/sarah.jpg", "alt_text": "sarah", "title": "Sarah", "artist": "J. Grant Merrill", "medium": "Pastel", "type": "Painting", "width": "", "height": "", "date_created": "2023-07-01", "collections": "", "status": "available", "price": ""},
 {"thumb_image": "images/Portraits/self_portrait.jpg", "full_image": "images/Full-Gallery/self_portrait.jpg", "alt_text": "self_portrait", "title": "Self Portrait", "artist": "J. Grant Merrill", "medium": "Oil", "type": "Painting", "width": "16.0", "height": "20.0", "date_created": "2024-04-01", "collections": "", "status": "not_for_sale", "price": ""},
 {"thumb_image": "images/Portraits/the_banjo_player.jpg", "full_image": "images/Full-Gallery/the_banjo_player.jpg", "alt_text": "the_banjo_player", "title": "The Banjo Player", "artist": "J. Grant Merrill", "medium": "Oil", "type": "Painting", "width": "11.0", "height": "14.0", "date_created": "2025-06-01", "collections": "", "status": "sold", "price": ""},
 {"thumb_image": "images/Portraits/pete_pastel_portrait.jpg", "full_image": "images/Full-Gallery/pete_pastel_portrait.jpg", "alt_text": "Pete Pastel Portrait", "title": "Pete Pastel Portrait", "artist": "J. Grant Merrill", "medium": "Pastel", "type": "Pastel", "width": "12", "height": "16", "date_created": "2023-10-21", "collections": "Portraits", "status": "not_for_sale", "price": ""},
 {"thumb_image": "images/Portraits/juna.jpg", "full_image": "images/Full-Gallery/juna.jpg", "alt_text": "Juna", "title": "Juna", "artist": "J. Grant Merrill", "medium": "Oil", "type": "Painting", "width": "14", "height": "11", "date_created": "2024-04-21", "collections": "Pets", "status": "sold", "price": ""},
 {"thumb_image": "images/Portraits/loyalty.jpg", "full_image": "images/Full-Gallery/loyalty.jpg", "alt_text": "Loyalty", "title": "Loyalty", "artist": "J. Grant Merrill", "medium": "Oil", "type": "Painting", "width": "9", "height": "12", "date_created": "2025-05-21", "collections": "Pets", "status": "sold", "price": ""},
 {"thumb_image": "images/Portraits/abbey_road_crossing.jpg", "full_image": "images/Full-Gallery/abbey_road_crossing.jpg", "alt_text": "Abbey_Road_Crossing", "title": "Abbey Road Crossing", "artist": "J. Grant Merrill", "medium": "Oil", "type": "Painting", "width": "36", "height": "24", "date_created": "2025-01-21", "collections": "Portraits", "status": "sold", "price": 900.0},
 {"thumb_image": "images/Portraits/alden_pastel_portrait.jpg", "full_image": "images/Full-Gallery/alden_pastel_portrait.jpg", "alt_text": "Alden Pastel Portrait", "title": "Alden Pastel Portrait", "artist": "J. Grant Merrill", "medium": "Pastel", "type": "Painting", "width": "12", "height": "16", "date_created": "2024-12-10", "collections": "Portraits", "status": "not_for_sale", "price": ""},
];
